In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
df  = pd.read_csv("data.csv")

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   gender               100000 non-null  str
 1   age                  100000 non-null  float64
 2   hypertension         100000 non-null  int64
 3   heart_disease        100000 non-null  int64
 4   smoking_history      100000 non-null  str
 5   bmi                  100000 non-null  float64
 6   HbA1c_level          100000 non-null  float64
 7   blood_glucose_level  100000 non-null  int64
 8   diabetes             100000 non-null  int64
dtypes: float64(3), int64(4), str(2)
memory usage: 8.0 MB

In [4]:
df.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0

In [5]:
# ------------------ CHECK FOR DUPLICATE VALUES ------------------

df.duplicated().value_counts()

False    96146
True      3854
Name: count, dtype: int64

In [7]:
df = df.drop_duplicates()

In [8]:
df.info()

<class 'pandas.DataFrame'>
Index: 96146 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   gender               96146 non-null  str
 1   age                  96146 non-null  float64
 2   hypertension         96146 non-null  int64
 3   heart_disease        96146 non-null  int64
 4   smoking_history      96146 non-null  str
 5   bmi                  96146 non-null  float64
 6   HbA1c_level          96146 non-null  float64
 7   blood_glucose_level  96146 non-null  int64
 8   diabetes             96146 non-null  int64
dtypes: float64(3), int64(4), str(2)
memory usage: 8.4 MB

In [9]:
# ------------------ HANDLE MISSING VALUES ------------------
print("\nMissing Values:\n", df.isnull().sum())

Missing Values:
 gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

In [10]:
# ------------------ ENCODING ------------------
# Using manual mapping (best use when consistency needed)

gender_map = {'Male': 0, 'Female': 1, 'Other': 2}
df['gender'] = df['gender'].map(gender_map)

In [11]:
df.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,1,80.0,0,1,never,25.19,6.6,140,0
1,1,54.0,0,0,No Info,27.32,6.6,80,0
2,0,28.0,0,0,never,27.32,5.7,158,0
3,1,36.0,0,0,current,23.45,5.0,155,0
4,0,76.0,1,1,current,20.14,4.8,155,0

 1.Why 'not current' and 'ever' = 2
     Person has smoking history but is not clearly current
     That’s why they’re grouped as 2 (mid-level risk category)

 2. why No Info = -1
     This is done to represent missing or unknown data

In [12]:


smoking_map = {
    'never': 0,
    'former': 1,
    'not current': 2,
    'current': 3,
    'ever': 2,
    'No Info': -1
}
df['smoking_history'] = df['smoking_history'].map(smoking_map)

In [13]:
# ------------------ VERIFY DATA ------------------
print("\nAfter Cleaning:")
print(df.head())
print(df.info())

After Cleaning:
   gender   age  hypertension  heart_disease  smoking_history    bmi  \
0       1  80.0             0              1                0  25.19
1       1  54.0             0              0               -1  27.32
2       0  28.0             0              0                0  27.32
3       1  36.0             0              0                3  23.45
4       0  76.0             1              1                3  20.14

   HbA1c_level  blood_glucose_level  diabetes
0          6.6                  140         0
1          6.6                   80         0
2          5.7                  158         0
3          5.0                  155         0
4          4.8                  155         0
<class 'pandas.DataFrame'>
Index: 96146 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   gender               96146 non-null  int64
 1   age                  96146 non-null  float64
 2   hypertension         96146 non-null  int64
 3   heart_disease        96146 non-null  int64
 4   smoking_history      96146 non-null  int64
 5   bmi                  96146 non-null  float64
 6   HbA1c_level          96146 non-null  float64
 7   blood_glucose_level  96146 non-null  int64
 8   diabetes             96146 non-null  int64
dtypes: float64(3), int64(6)
memory usage: 7.3 MB
None

In [14]:
# ------------------ SAVE CLEAN DATA ------------------
df.to_csv("clean_data.csv", index=False)

print("\n✅ Clean data saved as clean_data.csv")

✅ Clean data saved as clean_data.csv